Add Manufacturers names in debloat lists
0x192/Universal-Android-Debloater pull request #363
Opened 2022-08-27 04:49 UTC by soulspark666

Add Manufactures in the Manufactures list in readme according to PR

2022-08-27 13:38 UTC, AnonymousWP requested changes

2022-08-27 13:38 UTC, AnonymousWP commented on README.md
> +* [ ] Realme
```suggestion
* [x] Realme
```

Realme is already supported with some packages, plus it uses a lot of the same apps as on OPPO phones. What do you think?

2022-09-12 11:14 UTC, AnonymousWP requested changes

2022-09-12 11:14 UTC, AnonymousWP commented on README.md
>  * [X] Nokia
```suggestion
* [X] Nokia
* [X] Nothing
```

See https://github.com/0x192/universal-android-debloater/issues/381 and https://github.com/0x192/universal-android-debloater/issues/381#issuecomment-1243579483.

2022-09-16 09:08 UTC, AnonymousWP approved these changes

2022-11-13 00:32 UTC, merged

2022-11-13 00:33 UTC, 0x192 commented
Thanks! :tada: