Update uad_lists.json
0x192/Universal-Android-Debloater pull request #454
Opened 2022-11-26 15:19 UTC by HamidChikh

Sume.nn description

2022-11-26 15:20 UTC, HamidChikh commented
Editing

2022-11-28 11:18 UTC, AnonymousWP requested changes

2022-11-28 11:18 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Manages system resources (Performance/Battery) in Samsung phones. Removing this package won't break your phone, but the changes in performance are unclear",
```suggestion
    "description": "Manages system resources (performance/battery) of Samsung phones.\nIt's accountable to keep an eye on the running services in the background and force close them to boost or maintain the performance of the device.\nRemoving this package won't break your phone, but the changes regarding performance are unclear",
```

2022-12-17 21:35 UTC, 0x192 commented
Thanks for your contribution. The description was wrong tho :slightly_smiling_face: 

I decompiled after decompiling the APK and I could confirm [this comment](https://libreddit.spike.codes/r/androidapps/comments/p6fh8w/does_anyone_know_what_is_sumenn/il3rv2t/?context=3) on Reddit.


The new description :
> Provides the photo remaster feature in the Gallery app. Has the camera permission and can access all your medias but performs its job locally on the device.
https://www.samsung.com/au/support/mobile-devices/remastering-photos-on-samsung-phone/",

2022-12-17 21:45 UTC, merged