added warning and changed removal type to advance for …
0x192/Universal-Android-Debloater pull request #475
Opened 2022-12-26 19:34 UTC by gs1719

…oshare

Since it break the functionality of sharing the screenshot directly may disturb some user

2023-01-09 13:22 UTC, AnonymousWP requested changes

2023-01-09 13:22 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Oppo application Market .Safe to remove unless you are using it",
```suggestion
    "description": "Oppo application Market. Safe to remove unless you are using it.\nhttps://developers.oppomobile.com/newservice/capability?pagename=app_store",
```

2023-01-09 13:22 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Oppo Share\nFile sharing app to transfer data from/to Oppo devices only. Seems to use weak crypto (AES ECB mode) and has weird permissions (READ_CONTACTS ? Really ?).\n[Warning]Ma
```suggestion
    "description": "Oppo Share\nFile sharing app to transfer data from/to Oppo devices only. Seems to use weak crypto (AES ECB mode) and has weird permissions (such as `READ_CONTACTS`).\n[Warning]May break the functionality to share photos from oem photos app only and share with send prompt after screenshot is not working (though screenshot is saved and could be send through different similar application)\nPithus analysis: https://beta.pithus.org/report/170f4a14be24a2e2135cd956a038aae9e2f78c845f3161b84c5545dbec03fad9",
```

2023-01-11 08:52 UTC, AnonymousWP commented
@gs1719 Why are you closing it?? It needs to get merged by @0x192 first.

2023-01-11 10:00 UTC, gs1719 commented
Actually I am new in this 
Not able to understand what to do with suggestions so that's why I close it 
Should I reopen it or what to do to make changes?

2023-01-11 15:54 UTC, AnonymousWP commented
This is how you do it, and you're not supposed to close my suggestions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request. Don't close the pull request either, but commit the suggestions I've made.

2023-01-11 19:03 UTC, AnonymousWP approved these changes

2023-04-10 10:52 UTC, merged

2023-04-10 10:54 UTC, 0x192 commented
Sorry for the lag! It's finally merged! :slightly_smiling_face: