Added google personal safety
0x192/Universal-Android-Debloater pull request #484
Opened 2022-12-30 21:55 UTC by mmrabbani

I added a new bloatware I see after I updated. I disabled it successfully without side-effect.
It seems It is safe to remove. you can see play store link.
https://play.google.com/store/apps/details?id=com.google.android.apps.safetyhub

2023-01-09 13:48 UTC, AnonymousWP requested changes

2023-01-09 13:48 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Google personal safety (https://play.google.com/store/apps/details?id=com.google.android.apps.safetyhub). Personal Safety is a app that helps you prepare and react in an emergency
```suggestion
    "description": "Personal Safety (https://play.google.com/store/apps/details?id=com.google.android.apps.safetyhub)\nPersonal Safety is a Pixel app that helps you prepare and react in an emergency by quickly connecting you with the help and information you need.",
```

2023-01-10 22:24 UTC, AnonymousWP approved these changes

2023-04-10 15:17 UTC, merged

2023-04-10 15:18 UTC, 0x192 commented
Thanks! :+1: