Add description to `com.samsung.android.mcfds`
0x192/universal-android-debloater pull request #543
Opened 2023-02-02 18:12 UTC by Rudxain

This also changes `Expert` to `Advanced`, rather than `Recommended`, for safety reasons

2023-02-02 22:19 UTC, AnonymousWP requested changes

2023-02-02 22:19 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "list": "OEM",
```suggestion
    "list": "Oem",
```
Pretty sure it's case sensitive, so it should be like this instead.

2023-02-03 09:49 UTC, AnonymousWP approved these changes

2026-01-10 12:31 UTC, Rudxain commented
Universal-Debloater-Alliance/universal-android-debloater-next-generation#46

2026-01-10 12:31 UTC, closed without merging