add Samsung Talkback description
0x192/universal-android-debloater pull request #547
Opened 2023-02-03 05:00 UTC by Rudxain

ID: com.samsung.android.accessibility.talkback

2023-02-03 09:48 UTC, AnonymousWP requested changes

2023-02-03 09:48 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "list": "OEM",
```suggestion
    "list": "Oem",
```

2023-02-03 12:54 UTC, Rudxain commented
I forgot about the "OEM" thing twice, lol. Sorry for the mistake

2023-02-03 13:10 UTC, AnonymousWP approved these changes

2026-01-10 12:52 UTC, Rudxain commented
- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/d1ad1b1c092e86b2499c53c125c355fc6867a882
- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/44
- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/1247

2026-01-10 12:52 UTC, closed without merging