Add some informations for google photos
0x192/universal-android-debloater pull request #696
Opened 2023-04-12 11:19 UTC by Tontonjo

On my Nothing phone, this app is used to quick edit screens captures which is getting broken if this package is removed

2023-04-12 22:28 UTC, AnonymousWP requested changes

2023-04-12 22:28 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Google Photos (https://play.google.com/store/apps/details?id=com.google.android.apps.photos), May break screen capture quick edit if removed",
```suggestion
    "description": "Google Photos (https://play.google.com/store/apps/details?id=com.google.android.apps.photos)\nMay break screen capture quick edit if removed.",
```

Also, maybe you can change the removal to `advanced`?

2023-04-30 10:34 UTC, AnonymousWP commented
Can you still change the removal if required?

2023-04-30 15:28 UTC, Tontonjo commented
> 
Sorry what do you mean?

2023-05-01 16:42 UTC, AnonymousWP commented
> > 
> 
> Sorry what do you mean?

See https://github.com/0x192/universal-android-debloater/wiki/FAQ#how-are-the-recommendations-chosen

2023-05-01 16:52 UTC, Tontonjo commented
> > > 
> > 
> > 
> > Sorry what do you mean?
> 
> See https://github.com/0x192/universal-android-debloater/wiki/FAQ#how-are-the-recommendations-chosen

I've read it but i still cant understand "cant you still change the removal" in the given context.
If you're talking about the recommendation which your link points to, i'd say it may be rated under "Expert", but i guess it depends on the app used by default by the phone in order to quick edit.

2023-05-04 19:43 UTC, AnonymousWP commented
> > > > 
> > > 
> > > 
> > > Sorry what do you mean?
> > 
> > 
> > See https://github.com/0x192/universal-android-debloater/wiki/FAQ#how-are-the-recommendations-chosen
> 
> I've read it but i still cant understand "cant you still change the removal" in the given context. If you're talking about the recommendation which your link points to, i'd say it may be rated under "Expert", but i guess it depends on the app used by default by the phone in order to quick edit.
> 
> If you're asking if the package can easilly be reactivated: the answer is yes.

With `removal` (which is the name of the key in the JSON file) to indicate the recommendation, yeah. Maybe you can change it to `expert`, but mention it in the description that it depends whether you set the app as default or not.

2023-07-30 12:53 UTC, closed without merging

2023-07-30 22:21 UTC, AnonymousWP commented
@Tontonjo Why did you do this?

2023-07-31 09:50 UTC, Tontonjo commented
> @Tontonjo Why did you do this?

Oupsy, forgot about that, i was doing some cleanings in my repo's....