Delete google safety center
0x192/universal-android-debloater pull request #745
Opened 2023-05-22 03:52 UTC by equwal

One small step for privacy
One giant leap for bloatware

2023-05-22 03:58 UTC, equwal commented
Might want to do more testing before pulling this one in, this app does a lot of stuff.

2023-05-22 07:05 UTC, AnonymousWP requested changes

2023-05-22 07:05 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Google safety center anti-virus spyware\n(https://safety.google). Disables the 'Please enable google play\nprotect' prompt when installing from F-Droid after disabling it in the\n
```suggestion
    "description": "Google Safety Center (https://safety.google). Disables the 'Please enable Google Play/Protect' prompt when installing from F-Droid after disabling it in the Play Store. Probably also disables Gmail and browser malware notifications.\nUse a libre spam-blocking and DNS-blocking solution instead.",
```
I think you're using `\n` wrong. It's not a slash, but a new line, see https://www.w3schools.com/c/c_newline.php.

2023-05-22 18:21 UTC, equwal commented
Update, it doesn't actually remove the "please enable google play protect" pop-up. I wonder what it actually does.

2023-05-22 18:22 UTC, equwal commented on resources/assets/uad_lists.json
> +    "description": "Google safety center anti-virus spyware\n(https://safety.google). Disables the 'Please enable google play\nprotect' prompt when installing from F-Droid after disabling it in the\n
Looks good to me.

2023-05-22 18:23 UTC, equwal commented
Going to change the description and make it "advanced" since we don't know if it is really safe.

2023-05-22 18:29 UTC, equwal commented on resources/assets/uad_lists.json
> +    "description": "Google safety center anti-virus spyware\n(https://safety.google). Disables the 'Please enable google play\nprotect' prompt when installing from F-Droid after disabling it in the\n
Should I use \n after a certain number of characters, or just let UAD decide how to wrap my text?

2023-05-24 07:41 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Google safety center anti-virus spyware\n(https://safety.google). Disables the 'Please enable google play\nprotect' prompt when installing from F-Droid after disabling it in the\n
You'll have to decide that yourself. I usually insert a line break before a URL or after ~2 sentences.

2023-05-24 07:42 UTC, AnonymousWP requested changes

2023-05-24 07:42 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Related to Google Safety Center (https://safety.google). Probably effects malware detection in new app installs, gmail, and chrome. Use a libre spam-blocking and DNS-blocking solu
```suggestion
    "description": "Related to Google Safety Center (https://safety.google). Probably affects malware detection in new app installs, Gmail, and Chrome. Alternatively, you can use a libre spam-blocking and DNS-blocking solution instead.",
```

Don't think you should indirectly force users to use something else. It's up to the user.

2023-05-24 07:44 UTC, AnonymousWP requested changes

2023-05-24 07:44 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
Yeah, maybe advanced is better, as it's the only (default) security suite that's built-in. Disabling increases the attack surface for a user.

2023-05-25 04:37 UTC, equwal commented
Solid edits, should be ready.

2023-05-25 07:32 UTC, AnonymousWP approved these changes

2025-09-06 20:35 UTC, closed without merging