Remove Data Transfer to Google Pixel system app
0x192/universal-android-debloater pull request #748
Opened 2023-05-22 03:53 UTC by equwal

Amazing that they'd just install that on everyone's phone by default.

2023-05-22 06:57 UTC, AnonymousWP requested changes

2023-05-22 06:57 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Migrate data to your new pixel device with a usb-c cable or whatever. Best removed. Apparently it doesn't\nwork very well anyway.\n\n(https://play.google.com/store/apps/details?id
```suggestion
    "description": "Migrate data to your new Pixel device with a USB-C cable or whatever. Best removed. Apparently it doesn't work very well anyway.\nhttps://play.google.com/store/apps/details?id=com.google.android.apps.pixelmigrate",
```
What do you mean with "best removed"?

2023-05-22 18:31 UTC, equwal commented on resources/assets/uad_lists.json
> +    "description": "Migrate data to your new pixel device with a usb-c cable or whatever. Best removed. Apparently it doesn't\nwork very well anyway.\n\n(https://play.google.com/store/apps/details?id
By "best removed", I meant "It is best to remove this".

2023-05-24 08:20 UTC, AnonymousWP approved these changes

2025-09-06 20:36 UTC, closed without merging